// Code generated by 'guts'. DO NOT EDIT.

// From dto/ws.go
/**
 * Event: WS_AGENT_RESPONSE
 */
export interface AgentResponse {
    id: string;
    session_id: string;
    // interface type, falling back to unknown
    // this is likely an enum in an external package "github.com/smtdfc/nagare/shared/messages.Message"
    message: unknown;
}

// From dto/api.go
export interface ApiError {
    name: string;
    message: string;
    details?: Record<string, string> | null;
}

// From dto/api.go
export interface ApiResponse<T extends any> {
    data?: T;
    status: string;
    error?: ApiError | null;
}

// From dto/auth.go
export interface AuthPayload {
    id: string;
}

// From dto/api.go
export interface CheckHealthResponse {
    cpu: number;
    memory: number;
    uptime: number;
    status: string;
}

// From dto/api.go
export interface CreateProviderRequest {
    compatible: string;
    name: string;
    base_url: string;
    api_key: string;
    is_enable: boolean;
    available_models: string[];
}

// From dto/api.go
export interface CreateProviderResponse {
}

// From dto/ws.go
/**
 * Event: WS_CREATE_SESSION_FAILED
 */
export interface CreateSessionFailed {
    cause: string;
}

// From dto/ws.go
/**
 * Event: WS_CREATE_SESSION_SUCCESS
 */
export interface CreateSessionSuccess {
    id: string;
}

// From dto/api.go
export interface DeleteProviderRequest {
    id: string;
}

// From dto/api.go
export interface DeleteProviderResponse {
}

// From dto/api.go
export interface FetchModelRequest {
    compatible: string;
    base_url: string;
    api_key: string;
}

// From dto/api.go
export interface FetchModelResponse {
    models: string[];
}

// From dto/api.go
export interface GeneralSettings {
    current_provider: string;
    current_model: string;
}

// From dto/api.go
export interface GetGeneralSettingsResponse {
    settings: GeneralSettings | null;
}

// From dto/api.go
export interface GetListProviderResponse {
    providers: ProviderInfo[];
}

// From dto/api.go
export interface GetProviderByIDRequest {
    id: string;
}

// From dto/api.go
export interface GetProviderByIDResponse {
    provider: Provider;
}

// From dto/ws.go
/**
 * Event: WS_INVOKE_AGENT
 */
export interface InvokeAgent {
    id: string;
    session_id: string;
    text: string;
}

// From dto/ws.go
/**
 * Event: WS_INVOKE_AGENT_FAILED
 */
export interface InvokeAgentFailed {
    id: string;
    cause: string;
}

// From dto/api.go
export interface Provider {
    id: string;
    compatible: string;
    name: string;
    base_url: string;
    is_enable: boolean;
    available_models: string[];
    api_key: string;
}

// From dto/api.go
export interface ProviderInfo {
    id: string;
    compatible: string;
    name: string;
    base_url: string;
    is_enable: boolean;
    available_models: string[];
}

// From dto/api.go
export interface SaveGeneralSettingsRequest {
    settings: GeneralSettings | null;
}

// From dto/api.go
export interface SaveGeneralSettingsResponse {
}

// From dto/api.go
export interface UpdateProviderRequest {
    id: string;
    compatible: string;
    name: string;
    base_url: string;
    api_key: string;
    is_enable: boolean;
    available_models: string[];
    model_name: string;
}

// From dto/api.go
export interface UpdateProviderResponse {
}

// From dto/ws.go
export enum WsEvent {
    WS_AGENT_RESPONSE = "WS_AGENT_RESPONSE",
    WS_CREATE_SESSION = "WS_CREATE_SESSION",
    WS_CREATE_SESSION_FAILED = "WS_CREATE_SESSION_FAILED",
    WS_CREATE_SESSION_SUCCESS = "WS_CREATE_SESSION_SUCCESS",
    WS_INVOKE_AGENT = "WS_INVOKE_AGENT",
    WS_INVOKE_AGENT_FAILED = "WS_INVOKE_AGENT_FAILED"
}

// From dto/ws.go
export interface WsMessage<T extends any> {
    event: WsEvent;
    payload: T;
}

