// Code generated by 'guts'. DO NOT EDIT.

// From messages/agent.go
export interface AgentResponse {
    id: string;
    type: MessageType;
    status: AgentResponseStatus;
    content: string;
}

// From messages/agent.go
export enum AgentResponseStatus {
    AGENT_RESPONSE_COMPLETED = "AGENT_RESPONSE_COMPLETED",
    AGENT_RESPONSE_FAILED = "AGENT_RESPONSE_FAILED",
    AGENT_RESPONSE_STARTED = "AGENT_RESPONSE_STARTED"
}

// From messages/message.go
export type ListMessage = Message[];

// From messages/types.go
export enum MessageType {
    AGENT_RESPONSE = "AGENT_RESPONSE",
    REASONING_MESSAGE = "REASONING_MESSAGE",
    RESPONSE_COMPLETED_MESSAGE = "RESPONSE_COMPLETED_MESSAGE",
    RESPONSE_FAILED_MESSAGE = "RESPONSE_FAILED_MESSAGE",
    RESPONSE_STARTED_MESSAGE = "RESPONSE_STARTED_MESSAGE",
    TEXT_MESSAGE = "TEXT_MESSAGE",
    TOOL_CALL_MESSAGE = "TOOL_CALL_MESSAGE",
    TOOL_RESULT_MESSAGE = "TOOL_RESULT_MESSAGE"
}

// From messages/reasoning.go
export interface Reasoning {
    id: string;
    type: MessageType;
    content: string;
}

// From messages/response.go
export interface ResponseCompleted {
    id: string;
    type: MessageType;
}

// From messages/response.go
export interface ResponseFailed {
    id: string;
    type: MessageType;
    code: string;
    cause: string;
}

// From messages/response.go
export interface ResponseStarted {
    id: string;
    type: MessageType;
}

// From messages/role.go
export enum Role {
    AGENT = 0,
    DEVELOPER = 3,
    SYSTEM = 2,
    USER = 1
}

// From messages/text.go
export interface Text {
    id: string;
    type: MessageType;
    content: string;
    role: Role;
}

// From messages/tool.go
export interface ToolCall {
    id: string;
    type: MessageType;
    name: string;
    args: string;
    call_id: string;
}

// From messages/tool.go
export interface ToolCallResult {
    id: string;
    type: MessageType;
    call_id: string;
    result: string;
    error: string;
}

