package custom_errors

var (
	ErrAgentExecuteFailed             = NewNagareCoreError("AGENT_EXEC_FAILED", "Agent execute failed")
	ErrInvalidToolSchema              = NewNagareCoreError("INVALID_TOOL_SCHEMA", "Invalid tool schema")
	ErrModelNotSupportedByProvider    = NewNagareCoreError("MODEL_NOT_SUPPORTED", "Model not supported by provider")
	ErrGetListModelFailed             = NewNagareCoreError("GET_LIST_MODEL_FAILED", "Failed to get list of models")
	ErrModelQuotaExceed               = NewNagareCoreError("MODEL_QUOTA_EXCEED", "Model quota exceeded")
	ErrIncorrectToolArgs              = NewNagareCoreError("INCORRECT_TOOL_ARGS", "Incorrect tool arguments")
	ErrMarshalToolResultFailed        = NewNagareCoreError("MARSHAL_TOOL_RESULT_FAILED", "Failed to marshal tool result")
	ErrCreateUserSessionFailed        = NewNagareCoreError("CREATE_SESSION_FAILED", "Failed to create user session")
	ErrGetUserSessionFailed           = NewNagareCoreError("GET_SESSION_FAILED", "Failed to get user session")
	ErrSessionNotFound                = NewNagareCoreError("SESSION_NOT_FOUND", "Session not found")
	ErrGetChatHistoryFailed           = NewNagareCoreError("GET_CHAT_HISTORY_FAILED", "Failed to get chat history")
	ErrGetGeneralConfigFailed         = NewNagareCoreError("GET_GENERAL_CONFIG_FAILED", "Failed to get general config")
	ErrSetGeneralConfigFailed         = NewNagareCoreError("SET_GENERAL_CONFIG_FAILED", "Failed to set general config")
	ErrGetAllLLMProviderFailed        = NewNagareCoreError("GET_ALL_LLM_PROVIDER_FAILED", "Failed to get all LLM providers")
	ErrGetLLMProviderFailed           = NewNagareCoreError("GET_LLM_PROVIDER_FAILED", "Failed to get LLM provider")
	ErrAddLLMProviderFailed           = NewNagareCoreError("ADD_LLM_PROVIDER_FAILED", "Failed to add LLM provider")
	ErrDeleteLLMProviderFailed        = NewNagareCoreError("DELETE_LLM_PROVIDER_FAILED", "Failed to delete LLM provider")
	ErrProviderNotSupported           = NewNagareCoreError("PROVIDER_NOT_SUPPORTED", "LLM provider is not supported")
	ErrLLMProviderNotFound            = NewNagareCoreError("LLM_PROVIDER_NOT_FOUND", "LLM provider not found")
	ErrCurrentProviderNotSetup        = NewNagareCoreError("CURRENT_PROVIDER_NOT_SETUP", "Current LLM provider is not set up")
	ErrCurrentModelNotSetup           = NewNagareCoreError("CURRENT_MODEL_NOT_SETUP", "Current LLM model is not set up")
	ErrModelNotSupportedByLLMProvider = NewNagareCoreError("MODEL_NOT_SUPPORTED_BY_PROVIDER", "Model is not supported by this LLM provider")
	ErrLLMProviderAdapter             = NewNagareCoreError("LLM_PROVIDER_ADAPTER_ERROR", "LLM provider adapter error")
	ErrAgentLoop                      = NewNagareCoreError("AGENT_LOOP_ERROR", "Agent execution loop error")
	ErrAgentExceedMaxIterations       = NewNagareCoreError("AGENT_EXCEED_MAX_ITERATIONS", "Agent exceeded max iterations")
	ErrAgentChat                      = NewNagareCoreError("AGENT_CHAT_ERROR", "Agent chat process error")
	ErrGetListPluginFailed            = NewNagareCoreError("GET_LIST_PLUGIN_FAILED", "Failed to get list of plugins")
	ErrInstallPluginFailed            = NewNagareCoreError("INSTALL_PLUGIN_FAILED", "Failed to install plugin")
	ErrPluginNotFound                 = NewNagareCoreError("PLUGIN_NOT_FOUND", "Plugin not found")
	ErrLoadPluginMetadataFailed       = NewNagareCoreError("LOAD_PLUGIN_METADATA_FAILED", "Failed to load plugin metadata")
	ErrPluginMetadataInvalid          = NewNagareCoreError("PLUGIN_METADATA_INVALID", "Plugin metadata is invalid")
	ErrPluginBinaryMissing            = NewNagareCoreError("PLUGIN_BINARY_MISSING", "Plugin binary is missing")
	ErrStartPluginFailed              = NewNagareCoreError("START_PLUGIN_FAILED", "Failed to start plugin")
	ErrUnpackPluginFailed             = NewNagareCoreError("UNPACK_PLUGIN_FAILED", "Failed to unpack plugin")

	ErrUnknown = NewNagareCoreError("UNKNOWN_ERROR", "Unknown error occurred")
)
