/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsLlmProviderNewRouteImport } from './routes/settings/llm-provider/new'
import { Route as SettingsLlmProviderOverviewRouteImport } from './routes/settings/llm-provider/overview'
import { Route as SettingsLlmProviderEditIdRouteImport } from './routes/settings/llm-provider/edit/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLlmProviderNewRoute = SettingsLlmProviderNewRouteImport.update({
  id: '/settings/llm-provider/new',
  path: '/settings/llm-provider/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLlmProviderOverviewRoute =
  SettingsLlmProviderOverviewRouteImport.update({
    id: '/settings/llm-provider/overview',
    path: '/settings/llm-provider/overview',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsLlmProviderEditIdRoute =
  SettingsLlmProviderEditIdRouteImport.update({
    id: '/settings/llm-provider/edit/$id',
    path: '/settings/llm-provider/edit/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings/llm-provider/new': typeof SettingsLlmProviderNewRoute
  '/settings/llm-provider/overview': typeof SettingsLlmProviderOverviewRoute
  '/settings/llm-provider/edit/$id': typeof SettingsLlmProviderEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/llm-provider/new': typeof SettingsLlmProviderNewRoute
  '/settings/llm-provider/overview': typeof SettingsLlmProviderOverviewRoute
  '/settings/llm-provider/edit/$id': typeof SettingsLlmProviderEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings/llm-provider/new': typeof SettingsLlmProviderNewRoute
  '/settings/llm-provider/overview': typeof SettingsLlmProviderOverviewRoute
  '/settings/llm-provider/edit/$id': typeof SettingsLlmProviderEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings/llm-provider/new'
    | '/settings/llm-provider/overview'
    | '/settings/llm-provider/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/llm-provider/new'
    | '/settings/llm-provider/overview'
    | '/settings/llm-provider/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/settings/llm-provider/new'
    | '/settings/llm-provider/overview'
    | '/settings/llm-provider/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsLlmProviderNewRoute: typeof SettingsLlmProviderNewRoute
  SettingsLlmProviderOverviewRoute: typeof SettingsLlmProviderOverviewRoute
  SettingsLlmProviderEditIdRoute: typeof SettingsLlmProviderEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/llm-provider/new': {
      id: '/settings/llm-provider/new'
      path: '/settings/llm-provider/new'
      fullPath: '/settings/llm-provider/new'
      preLoaderRoute: typeof SettingsLlmProviderNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/llm-provider/overview': {
      id: '/settings/llm-provider/overview'
      path: '/settings/llm-provider/overview'
      fullPath: '/settings/llm-provider/overview'
      preLoaderRoute: typeof SettingsLlmProviderOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/llm-provider/edit/$id': {
      id: '/settings/llm-provider/edit/$id'
      path: '/settings/llm-provider/edit/$id'
      fullPath: '/settings/llm-provider/edit/$id'
      preLoaderRoute: typeof SettingsLlmProviderEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsLlmProviderNewRoute: SettingsLlmProviderNewRoute,
  SettingsLlmProviderOverviewRoute: SettingsLlmProviderOverviewRoute,
  SettingsLlmProviderEditIdRoute: SettingsLlmProviderEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
