// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateToken() {
  return window['go']['main']['App']['GenerateToken']();
}

export function GetRestApiConnect() {
  return window['go']['main']['App']['GetRestApiConnect']();
}

export function GetWebsocketConnect() {
  return window['go']['main']['App']['GetWebsocketConnect']();
}
