// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateToken():Promise<string>;

export function GetRestApiConnect():Promise<string>;

export function GetWebsocketConnect():Promise<string>;
