// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function ClearToken(): $CancellablePromise<void> {
    return $Call.ByID(2906583408);
}

export function GetHost(): $CancellablePromise<string> {
    return $Call.ByID(2167222352);
}

export function GetRestApiConnect(): $CancellablePromise<string> {
    return $Call.ByID(2824722994);
}

export function GetToken(): $CancellablePromise<string> {
    return $Call.ByID(3150796115);
}

export function GetWebsocketConnect(): $CancellablePromise<string> {
    return $Call.ByID(2641974317);
}

export function IsServerRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(288755184);
}

export function OpenPluginSelectDialog(): $CancellablePromise<string> {
    return $Call.ByID(3627948889);
}

export function SaveToken(token: string): $CancellablePromise<void> {
    return $Call.ByID(1204991788, token);
}

export function ShowErrorDialog(title: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(1717369371, title, message);
}
