name: Release Publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag to upload binaries to"
        required: true
        type: string

permissions:
  contents: write

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Nagare Bot
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.27"

      - name: Install Dix
        run: go install github.com/smtdfc/dix@latest

      - name: Build
        run: ./build.sh

      - name: Archive binaries
        run: |
          mkdir -p packed

          for dir in dist/*; do
            if [ -d "$dir" ]; then
              platform=$(basename "$dir")
              tar -czvf "packed/nagare-$platform.tar.gz" -C "$dir" .
            fi
          done

      - name: Upload binaries to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
