name: Release

on:
  push:
    branches:
      - release

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.27"
      - name: Install dix CLI
        run: |
          go install github.com/smtdfc/dix@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: npm install -g pnpm@12.4.1
          pnpm install

      - name: Build
        run: ./build.sh

      - name: Upload Linux amd64 Build
        uses: actions/upload-artifact@v4
        with:
          name: nagare-linux-build
          path: dist/linux-amd64

      - name: Upload Windows amd64 Build
        uses: actions/upload-artifact@v4
        with:
          name: nagare-windows-build
          path: dist/windows-amd64

      - name: Upload Darwin (macOS) amd64 Build
        uses: actions/upload-artifact@v4
        with:
          name: nagare-darwin-build
          path: dist/darwin-amd64

      - name: Upload Linux arm64 Build
        uses: actions/upload-artifact@v4
        with:
          name: nagare-linux-arm64
          path: dist/linux-arm64

      - name: Upload Darwin arm64 Build
        uses: actions/upload-artifact@v4
        with:
          name: nagare-darwin-arm64
          path: dist/darwin-arm64

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm semantic-release
